export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"主页\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"主页\",\"bgImage\":\"https://theme-hope-assets.vuejs.press/bg/6-light.svg\",\"bgImageDark\":\"https://theme-hope-assets.vuejs.press/bg/6-dark.svg\",\"bgImageStyle\":{\"background-attachment\":\"fixed\"},\"heroText\":\"bugfe 的进化历程\",\"tagline\":\"欢迎来到bugfe的博客！这是一个学习与成长的汇聚地，无论你是技术小白还是进阶大神，都能在这里找到你感兴趣的内容。希望这里能激发你的思考、点燃你的好奇，带你探索更多的知识领域。加入我们的学习之旅，让我们共同成长，收获智慧！\",\"actions\":null,\"highlights\":[{\"header\":null,\"bgImage\":\"/assets/bg/6-light.svg\",\"bgImageDark\":\"/assets/bg/6-dark.svg\",\"features\":[{\"title\":\"数据结构\",\"icon\":\"comment-dots\",\"details\":\"2024倾情制作，欢迎来lu！\",\"link\":\"https://theme-hope.vuejs.press/zh/guide/markdown/others.html#link-check\"},{\"title\":\"锁事壹二三\",\"icon\":\"box-archive\",\"details\":\"24呕心沥血，解开你心头的锁！\",\"link\":\"https://theme-hope.vuejs.press/zh/guide/markdown/container.html\"}]}],\"copyright\":false,\"footer\":\"<div class=\\\"content\\\"><a href=\\\"http://beian.miit.gov.cn\\\" target=\\\"_blank\\\">京ICP备1903****号</a> | MIT 协议, 版权所有 © 2023 bugfe，All rights reserved.</div>\",\"description\":\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"bugfe\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"主页\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"bugfe\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"主页\\\",\\\"description\\\":\\\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.29,\"words\":688},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
